services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./model:/app/model
    environment:
      - PYTHONPATH=/app

  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - API_URL=${API_URL:-https://f65e-20-212-171-173.ngrok-free.app}
    depends_on:
      - api
