# Render Blueprint for Frontend Only deployment
services:
  - type: web
    name: fraud-detection-frontend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run webapp/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_URL
        value: https://f65e-20-212-171-173.ngrok-free.app
      - key: PYTHONPATH
        value: .
